kind: Deployment
apiVersion: apps/v1
metadata:
  name: iot-data-receiver
  labels:
    app: iot-data-receiver
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iot-data-receiver
      tier: frontend
  template:
    metadata:
      labels:
        app: iot-data-receiver
        tier: frontend
    spec:
      containers:
      - name: iot-data-receiver
        image: localhost:5000/pushbuttonfun.com/iot-data-receiver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

        
---
kind: Service
apiVersion: v1
metadata:
  name: iot-data-receiver
  labels:
    app: iot-data-receiver
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000 
      targetPort: 3000 
  selector:
    app: iot-data-receiver
    tier: frontend
